### ISSUE TITLE
A display issue

### ISSUE THREAD

**Issue by franklinbill** [wenxin-wang/PulseDroidRtp#3] opened 2020-12-27 08:41 UTC
Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure, in the first page, the button and the following text overlap each other. This may be an adaptation problem. I suspect it is because **display and font size** are set to large (mainly due to **display size**).
Because of some problems with my eyesight, I often use the largest font and display.
![297165ECE247F4EDC808C49B7E0633F7](https://user-images.githubusercontent.com/18572115/103165857-dbaf8580-4857-11eb-9e22-120ae1901389.png)
App version is 1.0.1, my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, **_font size and display size are the largest ! ! !_**, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!
<img width="442" alt="bug-pulsedroidrtp" src="https://user-images.githubusercontent.com/18572115/103166981-3ea61a00-4862-11eb-9c99-3ad6b2db4318.png">

**Comment by wenxin-wang** [comment] 2020-12-27 11:49
Thank you for your feedback! I guess this problem can be fixed with a scrollable layout. I will look into it in a few days.

**Comment by franklinbill** [comment] 2020-12-31 09:24
Thanks*1000000 for your reply!

**Comment by wenxin-wang** [comment] 2020-12-31 12:05
I can reproduce the same problem on my phone. I just pushed a new version to F-Droid, let's wait for the server to build it, and see if the problem is fixed. Also, here is [the debug version](https://github.com/wenxin-wang/PulseDroidRtp/files/5757207/app-debug.zip) built on my PC, if you want to try before F-Droid gets updated.

**Comment by wenxin-wang** [comment] 2021-01-15 03:13
A gentle ping, new version can now be downloaded from F-Droid.

**Comment by wenxin-wang** [comment] 2021-05-16 02:35
Close for now. Feel free to reopen the issue if the problem's still there.

**Closed as completed** 2021-05-16 02:37 UTC
